refactor!: Remove pbench
This remove pbench code paths as it is no longer supported

Co-developed-by: Cursor

diff --git a/pyperf/pyperf_run b/pyperf/pyperf_run
--- a/pyperf/pyperf_run
+++ b/pyperf/pyperf_run
@@ -158,10 +158,6 @@ pip3_install()
 # to_home_root: home directory
 # to_configuration: configuration information
 # to_times_to_run: number of times to run the test
-# to_pbench: Run the test via pbench
-# to_pbench_copy: Copy the data to the pbench repository, not move_it.
-# to_puser: User running pbench
-# to_run_label: Label for the run
 # to_user: User on the test system running the test
 # to_sys_type: for results info, basically aws, azure or local
 # to_sysname: name of the system
@@ -287,54 +283,41 @@ while [[ $# -gt 0 ]]; do
 	esac
 done
 
-if [ $to_pbench -eq 0 ]; then
-	PYTHON_VERSION=$($python_exec --version | awk '{ print $2 }')
-	if [[ ${python_pkgs} != "" ]]; then
-		pkg_list=`echo $python_pkgs | sed "s/,/ /g"`
-		test_tools/package_install --packages "$python_pkgs" --no_packages $to_no_pkg_install
-	fi
-	if ! command -v $python_exec; then
-		exit_out "Error: Designated python executable, $python_exec, not present"
-	fi
-	pip3_install "pyperformance==$PYPERF_VERSION"
-	pip3_install psutil
-	pip3_install packaging
-	pip3_install pyparsing
-	pip3_install pyperf
-	pip3_install toml
+PYTHON_VERSION=$($python_exec --version | awk '{ print $2 }')
+if [[ ${python_pkgs} != "" ]]; then
+	pkg_list=`echo $python_pkgs | sed "s/,/ /g"`
+	test_tools/package_install --packages "$python_pkgs" --no_packages $to_no_pkg_install
+fi
+if ! command -v $python_exec; then
+	exit_out "Error: Designated python executable, $python_exec, not present"
+fi
+pip3_install "pyperformance==$PYPERF_VERSION"
+pip3_install psutil
+pip3_install packaging
+pip3_install pyparsing
+pip3_install pyperf
+pip3_install toml
 
-	cpus=`cat /proc/cpuinfo | grep processor | wc -l`
-	cous=1
-	mkdir python_results
-	
-	pyresults=python_results/pyperf_out_$(date "+%Y.%m.%d-%H.%M.%S")
+cpus=`cat /proc/cpuinfo | grep processor | wc -l`
+cous=1
+mkdir python_results
 
-	$python_exec -m pyperformance run --output  ${pyresults}.json
-	if [ $? -ne 0 ]; then
-		exit_out "Failed: $python_exec -m pyperformance run --output  ${pyresults}.json" 1
-	fi
-	
-	$python_exec -m pyperf dump  ${pyresults}.json > ${pyresults}.results
-	if [ $? -ne 0 ]; then
-		echo "Failed: $python_exec -m pyperf dump  ${pyresults}.json > ${pyresults}.results" 1
-		echo Failed > test_results_report
-	else
-		echo Ran > test_results_report
-	fi
+pyresults=python_results/pyperf_out_$(date "+%Y.%m.%d-%H.%M.%S")
 
-	generate_csv_file ${pyresults}
-else
-	source ~/.bashrc
-	arguments="${arguments} --test_iterations ${to_times_to_run}"
-	cd $curdir
-	echo $TOOLS_BIN/execute_via_pbench --cmd_executing "$0" $arguments --test ${test_name_run} --spacing 11 --pbench_stats $to_pstats
-	$TOOLS_BIN/execute_via_pbench --cmd_executing "$0" $arguments --test ${test_name_run} --spacing 11 --pbench_stats $to_pstats
-	if [ $? -ne 0  ]; then
-		exit_out "Failed: $TOOLS_BIN/execute_via_pbench --cmd_executing "$0" $arguments --test ${test_name_run} --spacing 11 --pbench_stats $to_pstats"
-	fi
-	exit 0
+$python_exec -m pyperformance run --output  ${pyresults}.json
+if [ $? -ne 0 ]; then
+	exit_out "Failed: $python_exec -m pyperformance run --output  ${pyresults}.json" 1
 fi
 
+$python_exec -m pyperf dump  ${pyresults}.json > ${pyresults}.results
+if [ $? -ne 0 ]; then
+	echo "Failed: $python_exec -m pyperf dump  ${pyresults}.json > ${pyresults}.results" 1
+	echo Failed > test_results_report
+else
+	echo Ran > test_results_report
+fi
+
+generate_csv_file ${pyresults}
 
 #
 # Process the data.
